ALTER TABLE `Order`
  ADD COLUMN `paymentMethod` VARCHAR(191) NOT NULL DEFAULT "",
  ADD COLUMN `deliveryTime` VARCHAR(191) NOT NULL DEFAULT "",
  ADD COLUMN `deliveryPlace` VARCHAR(191) NOT NULL DEFAULT "";